ktor:
  deployment:
    port: 8080

  application:
    modules:
      - com.featup.ApplicationKt.module

  database:
    driver: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/featsup"
    user: postgres
    password: nesantari
